import type { Director, Review } from '@/types/database'

export const FALLBACK_DIRECTORS: (Director & { imgUrl?: string })[] = [
  {
    id: 'director-1',
    name: '김○○',
    photo_url: '/images/director_1.png',
    title: '수석 장례지도사',
    position: '수석',
    years_experience: 15,
    introduction: '15년 이상의 경험을 바탕으로 고인과 유족 모두를 세심하게 배려합니다. 임종케어 전문가로서 마지막 순간을 평온하게 함께합니다.',
    specialties: ['임종케어', '화장절차', '가족상담'],
    phone: null,
    is_active: true,
    sort_order: 1,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    imgUrl: '/images/director_1.png',
  },
  {
    id: 'director-2',
    name: '이○○',
    photo_url: '/images/director_2.png',
    title: '장례지도사',
    position: '지도사',
    years_experience: 10,
    introduction: '다양한 종교의례 경험을 바탕으로 고인의 신앙에 맞는 예를 갖추어 진행합니다. 유족분들의 마음을 세심하게 살핍니다.',
    specialties: ['종교의례', '납골안치', '유족지원'],
    phone: null,
    is_active: true,
    sort_order: 2,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    imgUrl: '/images/director_2.png',
  },
  {
    id: 'director-3',
    name: '박○○',
    photo_url: '/images/director_3.png',
    title: '장례지도사',
    position: '지도사',
    years_experience: 8,
    introduction: '기업 단체 장례 및 해외 교포 장례 전문가입니다. 긴급 상황에서도 신속하고 전문적으로 대응합니다.',
    specialties: ['기업장례', '해외교포', '긴급출동'],
    phone: null,
    is_active: true,
    sort_order: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    imgUrl: '/images/director_3.png',
  },
]

type ReviewWithDirector = Review & { directors: { name: string } | null }

export const FALLBACK_REVIEWS: ReviewWithDirector[] = [
  {
    id: 'review-1',
    customer_name: '김○○',
    director_id: 'director-1',
    rating: 5,
    content: '갑작스러운 부친상에 너무 당황했는데, 담당 지도사님이 처음부터 끝까지 차분하게 안내해 주셨습니다. 후불제라 비용 걱정 없이 장례를 치를 수 있었어요. 진심으로 감사드립니다. 덕분에 아버지를 품위 있게 보내드릴 수 있었습니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2025-12-10T09:00:00Z',
    updated_at: '2025-12-10T09:00:00Z',
    directors: { name: '김○○' },
  },
  {
    id: 'review-2',
    customer_name: '이○○',
    director_id: 'director-2',
    rating: 5,
    content: '24시간 언제든지 연락이 되고, 새벽에도 즉시 출동해 주셨습니다. 전문적인 조언 덕분에 고인을 품위 있게 보내드릴 수 있었습니다. 유족 모두가 따뜻한 배려에 큰 위로를 받았어요. 휴앤올을 선택하길 정말 잘했습니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2026-01-05T14:30:00Z',
    updated_at: '2026-01-05T14:30:00Z',
    directors: { name: '이○○' },
  },
  {
    id: 'review-3',
    customer_name: '박○○',
    director_id: 'director-3',
    rating: 5,
    content: '회사에서 단체 상조를 통해 이용했습니다. 체계적이고 친절한 서비스에 임직원 모두가 만족했습니다. 기업 장례를 경험이 많으셔서 모든 절차가 매끄럽게 진행되었습니다. 앞으로도 꼭 휴앤올을 이용하겠습니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2026-02-03T11:00:00Z',
    updated_at: '2026-02-03T11:00:00Z',
    directors: { name: '박○○' },
  },
  {
    id: 'review-4',
    customer_name: '정○○',
    director_id: 'director-1',
    rating: 5,
    content: '어머니를 불교 예법에 맞게 모시고 싶었는데, 종교 의례를 세심하게 준비해 주셨습니다. 스님 섭외부터 49재 안내까지 모든 것을 도와주셔서 감사했습니다. 고인이 편안히 가셨을 것 같아 마음이 놓입니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2026-01-18T16:00:00Z',
    updated_at: '2026-01-18T16:00:00Z',
    directors: { name: '김○○' },
  },
  {
    id: 'review-5',
    customer_name: '최○○',
    director_id: null,
    rating: 4,
    content: '처음 장례를 치르는 거라 아무것도 몰랐는데, 행정 서류부터 화장장 예약까지 전부 대신 해주셨어요. 혼자였다면 정말 막막했을 텐데 든든한 전문가가 옆에 있어 주셔서 감사했습니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2025-11-22T10:00:00Z',
    updated_at: '2025-11-22T10:00:00Z',
    directors: null,
  },
  {
    id: 'review-6',
    customer_name: '한○○',
    director_id: 'director-2',
    rating: 5,
    content: '새벽 2시에 연락했는데도 30분 만에 도착해 주셨습니다. 긴급 상황에서 이렇게 빠르게 대응해 주시다니 정말 놀랐습니다. 이후 모든 과정도 전문적으로 진행해 주셔서 가족 모두가 감사하게 생각합니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2026-02-14T08:00:00Z',
    updated_at: '2026-02-14T08:00:00Z',
    directors: { name: '이○○' },
  },
  {
    id: 'review-7',
    customer_name: '윤○○',
    director_id: 'director-1',
    rating: 4,
    content: '수목장을 원했는데 적합한 곳을 찾고 예약까지 도와주셨습니다. 고인이 평소 자연을 좋아하셨는데 뜻에 맞게 보내드릴 수 있어 마음이 따뜻합니다. 세심한 배려에 감사드립니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2025-12-28T13:00:00Z',
    updated_at: '2025-12-28T13:00:00Z',
    directors: { name: '김○○' },
  },
  {
    id: 'review-8',
    customer_name: '장○○',
    director_id: 'director-3',
    rating: 5,
    content: '해외에 있다가 급하게 귀국했는데, 입국 전부터 모든 준비를 해주셨습니다. 멀리서 걱정하는 저희 가족을 위해 사진과 영상으로 상황을 공유해 주셔서 큰 위안이 되었습니다. 정말 감사합니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2026-01-30T15:00:00Z',
    updated_at: '2026-01-30T15:00:00Z',
    directors: { name: '박○○' },
  },
  {
    id: 'review-9',
    customer_name: '오○○',
    director_id: 'director-2',
    rating: 5,
    content: '후불제 서비스 덕분에 갑작스러운 상황에서도 비용 걱정 없이 장례를 치를 수 있었습니다. 처음부터 끝까지 한 분의 지도사님이 함께해 주셔서 중간에 설명을 반복할 필요도 없었어요. 최고의 서비스였습니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2026-02-08T12:00:00Z',
    updated_at: '2026-02-08T12:00:00Z',
    directors: { name: '이○○' },
  },
  {
    id: 'review-10',
    customer_name: '강○○',
    director_id: 'director-1',
    rating: 4,
    content: '기독교식 장례를 원했는데 목사님 섭외부터 예배 순서까지 꼼꼼하게 준비해 주셨습니다. 유족들이 슬픔에만 집중할 수 있도록 모든 실무를 대신해 주신 덕분에 진심으로 고인을 추모할 수 있었습니다.',
    image_urls: [],
    status: 'approved',
    admin_note: null,
    created_at: '2026-02-20T09:30:00Z',
    updated_at: '2026-02-20T09:30:00Z',
    directors: { name: '김○○' },
  },
]
